begin;
insert into businesstype (businesstype) values ('国有独资企业');
insert into businesstype (businesstype) values ('国有控股企业');
insert into businesstype (businesstype) values ('国有参股金企业');
insert into businesstype (businesstype) values ('国有');
insert into businesstype (businesstype) values ('集体企业');
insert into businesstype (businesstype) values ('股份合作企业');
insert into businesstype (businesstype) values ('联营企业');
insert into businesstype (businesstype) values ('有限责任公司');
insert into businesstype (businesstype) values ('股份有限公司');
insert into businesstype (businesstype) values ('私营企业');
insert into businesstype (businesstype) values ('港，澳，台投资企业');
insert into businesstype (businesstype) values ('港，澳，台合资企业');
insert into businesstype (businesstype) values ('港，澳，台独资企业');
insert into businesstype (businesstype) values ('港，澳，台投资股份有限企业');
insert into businesstype (businesstype) values ('外商投资企业');
insert into businesstype (businesstype) values ('中外合资企业');
insert into businesstype (businesstype) values ('外商投资股份有限公司');
commit;