//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guqin.Info.Data.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accountstatus
    {
        public Accountstatus()
        {
            this.useraccounts = new HashSet<UserAccount>();
        }
    
        public int idaccountStatus { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<UserAccount> useraccounts { get; set; }
    }
}
