//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guqin.Info.Data.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class business
    {
        public business()
        {
            this.products = new HashSet<product>();
        }
    
        public string name { get; set; }
        public System.DateTime foundTime { get; set; }
        public string despc { get; set; }
        public string owner { get; set; }
        public string logo { get; set; }
        public int userAccount { get; set; }
    
        public virtual businesstype businesstype { get; set; }
        public virtual useraccount useraccount1 { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
