//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guqin.Info.Data.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate
    {
        public string name { get; set; }
        public string desc { get; set; }
        public System.DateTime acheivedTime { get; set; }
        public int userAccount { get; set; }
    
        public virtual user user { get; set; }
    }
}
