//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guqin.Info.Data.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class majorcategory
    {
        public majorcategory()
        {
            this.submajorcategories = new HashSet<submajorcategory>();
        }
    
        public int idMajerCategory { get; set; }
        public string categoryName { get; set; }
    
        public virtual ICollection<submajorcategory> submajorcategories { get; set; }
    }
}
