//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guqin.Info.Data.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class productphoto
    {
        public int idProductPhoto { get; set; }
        public string ProductPhoto1 { get; set; }
        public int product { get; set; }
    
        public virtual product product1 { get; set; }
    }
}
