//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guqin.Info.Data.Production
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductionEntities : DbContext
    {
        public ProductionEntities()
            : base("name=ProductionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accountstatu> accountstatus { get; set; }
        public DbSet<accounttype> accounttypes { get; set; }
        public DbSet<business> businesses { get; set; }
        public DbSet<businesstype> businesstypes { get; set; }
        public DbSet<major> majors { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<productphoto> productphotoes { get; set; }
        public DbSet<stringtype> stringtypes { get; set; }
        public DbSet<student> students { get; set; }
        public DbSet<teacher> teachers { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<useraccount> useraccounts { get; set; }
        public DbSet<acheivement> acheivements { get; set; }
        public DbSet<certificate> certificates { get; set; }
    }
}
