//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guqin.Info.Data.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class stringtype
    {
        public stringtype()
        {
            this.products = new HashSet<product>();
        }
    
        public int idstringType { get; set; }
        public string stringType1 { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
