//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guqin.Info.Data.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class submajorcategory
    {
        public submajorcategory()
        {
            this.majors = new HashSet<major>();
        }
    
        public int idSubMajorCategory { get; set; }
        public string SubMajorCategoryName { get; set; }
        public int MajerCategory { get; set; }
    
        public virtual ICollection<major> majors { get; set; }
        public virtual majorcategory majorcategory { get; set; }
    }
}
