//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guqin.Info.Data.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class useraccount
    {
        public useraccount()
        {
            this.acheivements = new HashSet<acheivement>();
        }
    
        public int idUserAccount { get; set; }
        public string password { get; set; }
        public string registeredphonenum { get; set; }
        public string address { get; set; }
        public double latitude { get; set; }
        public double langtitude { get; set; }
        public int accountType { get; set; }
        public string contact { get; set; }
        public int accountStatus { get; set; }
        public string photo { get; set; }
    
        public virtual accountstatu accountstatu { get; set; }
        public virtual accounttype accounttype1 { get; set; }
        public virtual business business { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<acheivement> acheivements { get; set; }
    }
}
