//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guqin.Info.Data.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.certificates = new HashSet<certificate>();
        }
    
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string fullName { get; set; }
        public string gender { get; set; }
        public System.DateTime birthday { get; set; }
        public string headprotrait { get; set; }
        public int userAccount { get; set; }
        public System.DateTime expYear { get; set; }
    
        public virtual major major { get; set; }
        public virtual student student { get; set; }
        public virtual teacher teacher { get; set; }
        public virtual ICollection<certificate> certificates { get; set; }
        public virtual useraccount useraccount1 { get; set; }
    }
}
