//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guqin.Info.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity
    {
        public int idActivities { get; set; }
        public string name { get; set; }
        public int idProject { get; set; }
    
        public virtual project project { get; set; }
    }
}
