//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guqin.Info.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.activities = new HashSet<activity>();
            this.menus = new HashSet<menu>();
        }
    
        public int idProject { get; set; }
        public string projectName { get; set; }
    
        public virtual ICollection<activity> activities { get; set; }
        public virtual ICollection<menu> menus { get; set; }
    }
}
